### PR TITLE
Initial input and event manager

### PR DESCRIPTION
**Pull request by JavinalCharles**
Added the new InputManager class as well as the accompanying KeyboardControl component class and the KeyboardControlSystem class. I've tested out the new features in main source with the new Velocity component along with the accompanying MovementSystem. The current main should produce an executable that allows the player to move the avatar with WASD keys.

### CODE REVIEW

**Comment by formerlybased** [comment]
Code didn't compile, I think it's supposed to be SDL_Keycode, not SDL_KeyCode

**Comment by JavinalCharles** [comment]
Hrmm.. hold up. I'll check it out later but I'm pretty sure it compiled with me.

**Comment by JavinalCharles** [comment]
Yep. The thing compiles without a problem on my end. And it turns out, both SDL_Keycode and SDL_KeyCode is both with SDL_Keycode being the typedef to 32-bit integer while SDL_KeyCode being the enum.

Source Code: https://github.com/libsdl-org/SDL/blob/SDL2/include/SDL_keycode.h

**Comment by JavinalCharles** [comment]
I did change the music file being played by the game so maybe that's the problem? What errors were you having on your end?

**Comment by formerlybased** [comment]
Hm, odd. I get an error message sayin SDL_KeyCode doesn't exist, I wonder if it has to do with SDL version (althought that should be the same). Can I ask what platform you are building on?

**Comment by JavinalCharles** [comment]
Linux. Ubuntu 22.04

Maybe the error's in a source file you're working on? If a type is being used yet it doesn't exists, that's an indication of mistakenly not including a header file.

**Comment by formerlybased** [comment]
I'm on linux mint 20.3,  I wonder if I have an outdated version of SDL2... let me check

**Comment by formerlybased** [comment]
Hm, after some more testing I seem to be having problems with SDL2 in general on my device... let me check on another computer. We should probably enforce a minimum SDL version, also we can remove the lib/ and include/ directories, it seems like with a bit of modification to the CMakeLists.txt they are unnecessary.

**Comment by JavinalCharles** [comment]
Okay. I'll work on something else for now but @-me when you need something.

**Comment by formerlybased** [comment]
P.S. @JavinalCharles We can remove the old (unfinished) input system with this PR, just delete input.h and input.cpp

**Comment by JavinalCharles** [comment]
> It works if I switch it to SDL_Keycode, however it seems that binding an action for a held key or binding an action for a key release doesn't work. I wonder if it's a byproduct of the change to SDL_Keycode or if it doesn't work with SDL_KeyCode either.

Key Released work for me. Key Held doesn't, whatever I do. The reason being is that, even if you hold down on a key, there's no certainty that it will be polled by SDL_PollEvent in the next loop. So what happens if you hold on to say, Key 'W':

Previous Frame: 'W' is Polled.
This Frame: 'W' is NOT Polled
Next Frame: 'W' is Polled

I think the reason for this is that the current test game may be looping for SDL_PollEvent() to keep up. Which is expected since, nothing really much is happening in our test environment anyway.  I'm going to find other (better) ways to check for keys in the future PRs. I might also suggest that we somehow limit our frame rate somehow to something like 60fps if possible. For now though, I've implemented the following changes:

Removed InputManager::isKeyHeld()
Replaced with InputManager::isKeyActive() -- which just checks if the key is pressed in current frame
Modified InputManager::isKeyDown() -- which now returns true if the key is pressed in current frame but not in previous frame(recently pressed)
Replaces all known instances SDL_KeyCode with SDL_Keycode.

**Comment by JavinalCharles** [comment]
@formerlybased Also, removed input.h and input.cpp, :+1:

**Comment by formerlybased** [comment]
Seems good for now. We can work on the input system more in the future. Thanks a lot as always.

**Pull request merged**
