### PR TITLE
Create initial ECS framework

### PR DESCRIPTION
**Pull request by JavinalCharles**
In case people are using the old system, I opted not to touch the old source files and just created new ones in different sub-folders.

BTW, I haven't really compiled any of these yet so I don't know if the compilers will cry once we try, but my IDE doesn't seem to see any errors.

### CODE REVIEW

**Comment by formerlybased** [comment]
Hey, thanks a lot. Gonna see if it compiles, and then merge it,

**Comment by formerlybased** [comment]
@JavinalCharles Compiling gives me some errors mostly regarding #includes.  Let me check it out a bit more and see if I can fix it

**Comment by JavinalCharles** [comment]
:sob: Hold up. I got something. I DO have some errors. Let me fix it for a bit then commit later on.

**Comment by JavinalCharles** [comment]
@formerlybased There ya go. I've fixed all errors I can find and things seems to compile on my end. Let me know if there's some other problem.

**Review by formerlybased — APPROVED** [review]
Looks great, will merge soon. We should deprecate the old Entity system before the 1.0 release. I can start working on the Game class now. Thanks a lot!

**Pull request merged**
